name: build-iso
on:
  workflow_dispatch:

concurrency:
  # only run one build at a time
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

env:
  IMAGE_NAME: sticky-os
  IMAGE_REPO: "ghcr.io/${{ github.repository_owner }}"
  IMAGE_TAG: latest
  VARIANT: Kinoite

jobs:
  build-containwr-installer:
    name: Build & upload ISO
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image_suffix: ["", "-nvidia", "-nvidia-open"]
        version: [41]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Lowercase repo
        id: repo_case
        uses: ASzc/change-string-case-action@d0603cd0a7dd490be678164909f65c7737470a7f # v6
        with:
          string: ${{ env.IMAGE_REPO }}

      - name: Build ISO
        uses: jasonn3/build-container-installer@main
        id: iso
        with:
          image_name: ${{ env.IMAGE_NAME }}${{ matrix.image_suffix }}
          image_repo: ${{ steps.repo_case.outputs.lowercase }}
          image_tag: ${{ env.IMAGE_TAG }}
          version: ${{ matrix.version }}
          variant: ${{ env.VARIANT }}
          iso_name: ${{ env.IMAGE_NAME }}${{ matrix.image_suffix }}-${{ env.IMAGE_TAG }}-${{ matrix.version }}.iso

      - name: Upload ISO as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.iso.outputs.iso_name }}
          path: |
            ${{ steps.iso.outputs.iso_path }}
            ${{ steps.iso.outputs.iso_path }}-CHECKSUM
          if-no-files-found: error
          retention-days: 0
          compression-level: 0
